In [1]:
import tensorflow as tf

In [2]:
import numpy as np 

In [4]:
arr=np.array([[1,2,3,4],[4,5,6,0],[2,0,7,8],[3,7,4,2]])

In [5]:
gfg=tf.data.Dataset.from_tensor_slices(arr)

In [6]:
for i in gfg:
    print(i.numpy())

[1 2 3 4]
[4 5 6 0]
[2 0 7 8]
[3 7 4 2]


In [7]:
map(max,arr)

In [8]:
list(map(max,arr))

[4, 6, 8, 7]

In [9]:
v=tf.constant([[2,5,1],[7,12,4],[19,5,6]])
v2=tf.constant([[13,4,11],[67,23,45],[71,11,10]])

In [10]:
v3=v+v2

In [11]:
v3

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[15,  9, 12],
       [74, 35, 49],
       [90, 16, 16]])>

In [12]:
list=[[1,2,3],[2,3,4],[4,5,6]]

In [13]:
c=tf.add(list,v)

In [14]:
c

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 3,  7,  4],
       [ 9, 15,  8],
       [23, 10, 12]])>